// <auto-generated />
using CourseCreatorWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseCreatorWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240404181902_AddCoursesTableToDb")]
    partial class AddCoursesTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseCreatorWeb.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreditHours = 3,
                            Description = "An introduction to the fundamentals of computer science.",
                            Subject = "Computer Science",
                            Title = "Intro to Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            CreditHours = 3,
                            Description = "Introduction to calculus.",
                            Subject = "Math",
                            Title = "Calculus 1"
                        },
                        new
                        {
                            Id = 3,
                            CreditHours = 3,
                            Description = "Building a sophisticated, real-world application.",
                            Subject = "Computer Science",
                            Title = "Software Systems Capstone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
